[workspace]
resolver = "2"
members = ["packages/01", "packages/common"]

[workspace.dependencies]
cfg-if = "1.0.0"
env_logger = "0.10.0"
log = "0.4.20"
pollster = "0.3.0"
wgpu = "0.17.1"
winit = "0.28.7"
bytemuck = "1.14.0"