[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "commonlib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if.workspace = true
env_logger.workspace = true
log.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true
bytemuck.workspace = true
